
/**********************************************************************
 * @Name         : OSF_WeatherWrapperWeatherData
 * @Description  : Wrapper class for weather base data: description, icon
 *
 * @Created By   : Marta Demeny
 * @Created Date : 19 jun. 2022
 * @Modification Log: 
 ********************************************************************
 * Version		Developer		Date			Description
 *___________________________________________________________________
 *
 *********************************************************************/
public with sharing class OSF_WeatherWrapperWeatherData {
    public String description {get; set;}
    public String icon {get; set;}
}